---
title: "Scatterpots of MRI Pixel Values"
author: "Lanyu Zhang"
date: "2023-05-07"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(plyr) # adply
library(caret) # createDataPartition
library(glmnet) #cv.glmnet
library(imager)
```

```{r}
dataset <- read.csv("data/imagedatareducedby3.csv")
```

```{r}
select_vars <- function(dataset,
                        folds=10,
                        model=c("ANOVA","PCA","lasso"),
                        model_threshold=NA) {
  
  X <- dataset[,-ncol(dataset)]
  Y <- dataset$DX
  
  # Define 10-fold cross-validation
  folds_num <- createFolds(Y, k=folds)
  
  # Create empty list to store results for each fold
  res_list <- list()
  
  # Loop over folds
  for (i in 1:folds) {
  
  # 1-Partition data: Split data into training and test sets for this fold
  test_indices <- folds_num[[i]]
  train_indices <- setdiff(seq_along(Y), test_indices)
  X_train <- X[train_indices,]
  Y_train <- Y[train_indices]
  X_test <- X[test_indices,]
  Y_test <- Y[test_indices]
  
  ## remove vars with all zeros
  X_train <- X_train[,colSums(X_train==0)/nrow(X_train)*100 != 100]
  X_test <- X_test[,colnames(X_train)]
  # identical(colnames(X_train),colnames(X_test))
    
  if (model == "ANOVA") {
    res <- apply(
      X_train, 2, function(col){
        summary(aov(col~Y_train))[[1]]["Y_train","Pr(>F)"]
        }) %>% as.data.frame() %>%
      filter( . < model_threshold)
    
    res_list[[i]] <- row.names(res)
    
  } else if (model == "lasso") {
    Y_train_num <- case_when(
      Y_train == "Non Demented" ~ 0,
      Y_train == "Very Mild Demented" ~ 1,
      Y_train == "Mild Demented" ~ 2,
      Y_train == "Moderate Demented" ~ 3)
    
    fit <- cv.glmnet(X_train %>% as.matrix(), Y_train_num, alpha=1)
    coef_lasso <- coef(fit, s = fit$lambda.min)
    selected_vars <- coef_lasso %>% 
      as.matrix() %>% as.data.frame() %>%
      tibble::rownames_to_column(var = "RowNames") %>%
      filter(s1 != 0) %>% pull(RowNames)
    res_list[[i]] <- selected_vars[-1]
  } else if (model == "PCA") {
    pca_model <- prcomp(X_train, scale = TRUE)
    loadings <- pca_model$rotation
    top_vars_pc1 <- names(loadings[order(-abs(loadings[, 1]))[1:500], 1])
    top_vars_pc2 <- names(loadings[order(-abs(loadings[, 2]))[1:500], 2])
    res_list[[i]] <- unique(c(top_vars_pc1,top_vars_pc2))
  }
  }
  
  # Compute average of row names across all folds
  mean_row_names <- do.call(c, res_list) %>% table() %>% 
  as.data.frame() %>% filter(Freq == folds) %>% pull('.') %>% as.character()
  
  return(mean_row_names)
}

plot_mri <- function(dataset,mean_row_names) {
  
  # Plot one of the images
  averagepix <- colMeans(dataset[,-ncol(dataset)])
  image_mat <- matrix(averagepix,ncol=43,nrow=43)
  
  # Get column and row indices of selected variables
  location <- as.numeric(substr(mean_row_names, 2, nchar(mean_row_names)))
  selected_rows <- (location-1) %/% 43 + 1
  selected_cols <- (location-1) %% 43 + 1
  
  # Convert row and column indices to normalized coordinates
  x_norm <- (selected_cols - 1) / 42
  y_norm <- 1 - (selected_rows - 1) / 42
  
  # Initialize plot window
  # plot.new()
  
  # Plot image with points added by dimension reduction method
  image(image_mat, col = gray(0:256/256),xlim=c(0,1),ylim=c(0,1))
  points(x_norm, y_norm, col = "red", pch = 15, cex = 2)
  
}
```

```{r}
set.seed(100)
mean_row_names <- select_vars(dataset=dataset,model="ANOVA",model_threshold=10^(-90))
plot_mri(dataset=dataset,mean_row_names=mean_row_names)

set.seed(100)
mean_row_names <- select_vars(dataset=dataset,model="ANOVA",model_threshold=10^(-2))
plot_mri(dataset=dataset,mean_row_names=mean_row_names)


set.seed(100)
mean_row_names <- select_vars(dataset=dataset,model="PCA")
plot_mri(dataset=dataset,mean_row_names=mean_row_names)

set.seed(100)
mean_row_names <- select_vars(dataset=dataset,model="lasso")
plot_mri(dataset=dataset,mean_row_names=mean_row_names)
```

